### ISSUE TITLE
Class MEAAnalysis is created without any methods.

### ISSUE THREAD

**Issue by alinaheukamp** [neural-electrophysiology-tool-team/NET#9]
When I run "MA = MEAAnalysis(path-to-excelsheet)" and then check the methods (using "methods(MA)"), I get the message "No methods for class MEAAnalysis."
In an older version of the code it worked and I would get a list of methods.
I tried finding the issue but couldn't find any reason why it's not working.

**Comment by yuvalorsher** [comment]
Which matlab version are you using?
I have R2018b (9.5.0.944444) running on windows 10 and methods(MA) works for me.

**Comment by alinaheukamp** [comment]
I'm using R2019b (9.7.0.1190202) on Windows 10 and it's not working.

**Comment by yuvalorsher** [comment]
Can you make a new clone of the repository from Github, stay on the master branch, make sure only this repository is in the Matlab path and try again? If it still doesn't work, can you try with R2018b to see if it's a Matlab issue?

**Comment by alinaheukamp** [comment]
Done.

I made a new clone and made sure it's the only one in the path - still didn't work.
Now I am using a 30-day trial version for Matlab R2018b with exactly the same code and it works!
Thanks for that great suggestion. But aarrrggghhh Matllab! :(
